import { IdeaForm } from '@/components/idea-form/IdeaForm'

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center px-4 py-20 bg-[#FAF8F5]">
      <div className="w-full max-w-2xl flex flex-col gap-10">
        <div className="flex flex-col items-center gap-3 text-center">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#6B4C35] flex items-center justify-center text-sm font-bold text-white">
              F
            </div>
            <span className="text-sm font-semibold tracking-wide text-[#8C7B6B]">FounderOS</span>
          </div>

          <h1 className="text-3xl sm:text-4xl font-semibold text-[#1C1612] leading-tight">
            Your AI co-founder,<br />
            <span className="text-[#6B4C35]">ready in seconds</span>
          </h1>

          <p className="text-sm text-[#8C7B6B] max-w-md">
            Describe your startup idea and get a full startup infrastructure generated by Claude — pitch deck, marketing kit, investor memo, and financial model.
          </p>
        </div>

        <IdeaForm />

        <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-[#8C7B6B]/60">
          <span>◈ Pitch Deck</span>
          <span>◉ Marketing Kit</span>
          <span>◎ Investor Memo</span>
          <span>▣ Financial Model</span>
        </div>
      </div>
    </main>
  )
}
