import { IdeaForm } from '@/components/idea-form/IdeaForm'

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center px-4 py-20">
      <div className="fixed inset-0 bg-[radial-gradient(ellipse_at_top,_#1e1b4b_0%,_transparent_60%)] pointer-events-none" />

      <div className="relative w-full max-w-2xl flex flex-col gap-10">
        <div className="flex flex-col items-center gap-3 text-center">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center text-sm font-bold">
              F
            </div>
            <span className="text-sm font-semibold tracking-wide text-white/80">FounderOS</span>
          </div>

          <h1 className="text-3xl sm:text-4xl font-semibold text-white leading-tight">
            Your AI co-founder,<br />
            <span className="text-indigo-400">ready in seconds</span>
          </h1>

          <p className="text-sm text-white/40 max-w-md">
            Describe your startup idea and get a full startup infrastructure generated by Claude — pitch deck, marketing kit, investor memo, and financial model.
          </p>
        </div>

        <IdeaForm />

        <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-white/20">
          <span>◈ Pitch Deck</span>
          <span>◉ Marketing Kit</span>
          <span>◎ Investor Memo</span>
          <span>▣ Financial Model</span>
        </div>
      </div>
    </main>
  )
}
